<?php

namespace App\Filament\Resources\Transactions\Actions;

use Filament\Actions\Action;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\TextInput;
use Filament\Notifications\Notification;
use Filament\Schemas\Components\Section;
use Filament\Support\Icons\Heroicon;
use Illuminate\Support\Facades\Log;

class WithdrawAction extends Action
{
    public static function make(?string $name = null): static
    {
        return parent::make($name); // TODO: Change the autogenerated stub
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = auth()->user();
        $wallet = $user->wallet;
        $this
            ->tooltip('Withdraw From Wallet')
            ->color('indigo')
            ->label('Withdraw From Wallet')
            ->icon('hugeicons-money-send-flow-02')
            ->visible(fn () => $wallet->balance >= 150)
            ->slideOver()
            ->modalWidth('md')
            ->fillForm([
                'name' => $user->name,
                'phone' => $user->phone,
                'current_balance' => $wallet->balance,
                'amount' => null,
                'wallet_id' => $wallet->id,
            ])
            ->schema([
                Hidden::make('wallet_id'),
                Section::make('Customer Information')
                    ->schema([
                        TextInput::make('name')
                            ->label('Customer Name')
                            ->readonly()
                            ->prefixIcon(Heroicon::OutlinedUser)
                            ->prefixIconColor('primary'),

                        TextInput::make('phone')
                            ->label('Receiver Phone')
                            ->readonly()
                            ->prefixIcon(Heroicon::OutlinedPhone)
                            ->prefixIconColor('primary'),

                        TextInput::make('current_balance')
                            ->label('Current Balance')
                            ->readonly()
                            ->numeric()
                            ->prefix('KES')
                            ->prefixIcon(Heroicon::OutlinedCurrencyDollar)
                            ->prefixIconColor('primary'),
                    ]),
                Section::make('Amount To Withdraw')
                    ->schema([
                        TextInput::make('amount')
                            ->label('Amount To Withdraw')
                            ->required()
                            ->numeric()
                            ->minValue(0)
                            ->prefix('KES')
                            ->prefixIcon(Heroicon::OutlinedCurrencyDollar)
                            ->prefixIconColor('primary')
                            ->placeholder('Enter amount to withdraw'),
                    ]),
            ])
            ->action(function (array $data, $livewire) use ($wallet): void {
                try {
                    // Create withdrawal transaction, observer handles the rest
                    $wallet->transactions()->create([
                        'amount' => $data['amount'],
                        'type' => 'withdraw',
                    ]);
                    $livewire->resetTable();

                    Notification::make()
                        ->title('Withdraw Successful')
                        ->body('Withdrawal of Amount: '.$data['amount'].' was successful.')
                        ->success()
                        ->send();
                } catch (\Exception $e) {
                    Log::error('Withdraw Action failed: ', ['error' => $e->getMessage()]);

                    Notification::make()
                        ->title('Withdraw Failed')
                        ->body($e->getMessage())
                        ->danger()
                        ->send();

                    throw $e;
                }
            });

    }
}
