<?php

namespace App\Filament\Resources\Bugs\Actions;

use App\Enums\BugStatus;
use App\Models\Bug;
use Filament\Actions\Action;
use Filament\Notifications\Notification;

class FixedBugAction extends Action
{
    public static function make(?string $name = null): static
    {
        return parent::make($name); // TODO: Change the autogenerated stub
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this
            ->label('Bug Fixed')
            ->color('purple')
            ->icon('')
            ->requiresConfirmation()
            ->modalHeading('Mark Bug as Fixed')
            ->modalDescription('Are you sure you want to mark this bug as fixed? This will move it to pending confirmation.')
            ->modalSubmitActionLabel('Yes, Mark as Fixed')
            ->visible(fn (?Bug $bug) => $bug && ! $bug->is_paid && in_array($bug->status, [BugStatus::UNDER_REVIEW, BugStatus::CLOSED, BugStatus::REJECTED, BugStatus::SUBMITTED, BugStatus::DUPLICATE]))
            ->action(function (Bug $bug) {
                $bug->update([
                    'status' => BugStatus::FIXED,
                    'duplicate_of_id' => null,
                ]);
                Notification::make()
                    ->title('Bug Marked as Fixed')
                    ->body("Bug #{$bug->bug_no} has been marked as fixed.")
                    ->success()
                    ->send();
            });
    }
}
